Peek pop 対応
hhyyg/Miso.iOSPractice pull request #4
Opened 2017-12-06 07:34 UTC by hhyyg

- Peekで、詳細画面のプレビューを表示するように。そのままPopで詳細画面に遷移。
- puick quick action で、そのアイテムを削除できるように
- 他リファクタ

2017-12-06 08:07 UTC, mono0926 reviewed
![30_](https://user-images.githubusercontent.com/1255062/33651084-eb6c46f0-daa7-11e7-99a6-4afa7be08839.png)

2017-12-06 08:07 UTC, mono0926 commented on Miso.TrackingMealApp/TrackingMealApp/DataContainer.swift
> +        return [meal1, meal2, meal3]
Meal nameの[String]あたりを元に、mapとか使ってきれいに書けそう。

2017-12-06 08:07 UTC, mono0926 commented on Miso.TrackingMealApp/TrackingMealApp/DataContainer.swift
> +            fatalError("Unable to instantiate meal2")
> Meal nameの[String]あたりを元に、mapとか使ってきれいに書けそう。

meal2ではなく3だけど、こういうミスも防げるはず。

2017-12-06 08:07 UTC, mono0926 commented on Miso.TrackingMealApp/TrackingMealApp/MealTableViewController.swift
>      }
不使用の雛形メソッドは基本的に消す。

2017-12-06 08:07 UTC, mono0926 commented on Miso.TrackingMealApp/TrackingMealApp/MealTableViewController.swift
> +        return DataContainer.meals.count
各所で可変の`DataContainer.meals`を参照しているとタイミングで不整合起こりそうで不安。
reload前にプロパティにセットしてそれを参照する方が堅牢になりそう。

2017-12-06 08:07 UTC, mono0926 commented on Miso.TrackingMealApp/TrackingMealApp/MealTableViewController.swift
> +        return DataContainer.meals.count
と思ったけど、今の全体の作り的にはこれでいいかなあ 🤔

2017-12-06 08:07 UTC, mono0926 commented on Miso.TrackingMealApp/TrackingMealApp/MealTableViewController.swift
> +        let i = DataContainer.meals.index { $0.id == meal.id }!
容易にミスってクラッシュしそうだから、!使わずにguardしてassertしつつreturnくらいが妥当かな(開発時はassert引っかかって、リリース時はクラッシュせず動かないけどデータの整合性が直ったら動くようになる感じ)

2017-12-06 08:07 UTC, mono0926 commented on Miso.TrackingMealApp/TrackingMealApp/MealTableViewController.swift
> +        let i = DataContainer.meals.index { $0.id == meal.id }!
動的なデータとか絡む場合は、基本的に!系の操作しない方が良い。
初期化処理とかの開発時に絶対気づけそうなところは!で良いけど。

2017-12-06 08:07 UTC, mono0926 commented on Miso.TrackingMealApp/TrackingMealApp/MealViewController.swift
> +            self.delegate!.mealViewController(self, mealDeleteDidTap: self.meal!)
この!も、リリース時にこのパスで落としたいという明確な意思がない限り避けたい。

2017-12-07 03:15 UTC, hhyyg commented on Miso.TrackingMealApp/TrackingMealApp/MealTableViewController.swift
> +        return DataContainer.meals.count
今回のサンプルでは見逃したい

2017-12-07 03:15 UTC, hhyyg commented on Miso.TrackingMealApp/TrackingMealApp/MealTableViewController.swift
> +        let i = DataContainer.meals.index { $0.id == meal.id }!
なるほどです

2017-12-07 03:16 UTC, hhyyg commented on Miso.TrackingMealApp/TrackingMealApp/MealViewController.swift
> +            self.delegate!.mealViewController(self, mealDeleteDidTap: self.meal!)
直しました。`!`を多用してしまう気がする

2017-12-07 03:20 UTC, mono0926 commented on Miso.TrackingMealApp/TrackingMealApp/DataContainer.swift
> +        let sampleMeals: [Meal] = elements.map { (name, photoName, rating) in
enumerated()挟むと、mapの引数にindexが渡るから、"photoName\(i+1)"みたいに画像文字列組み立てられる。

2017-12-07 03:20 UTC, mono0926 commented on Miso.TrackingMealApp/TrackingMealApp/MealTableViewController.swift
> +            logger.debug("no found meal:\(meal.id) \(meal.name)")
こういう予期しない異常系はerror系のログ吐くのが普通。

2017-12-07 03:22 UTC, mono0926 commented on Miso.TrackingMealApp/TrackingMealApp/MealTableViewController.swift
> +            logger.debug("no found meal:\(meal.id) \(meal.name)")
あるいは、面倒だからとassertionFailure()で済ませることもよくある。
何れにしても、debugログだとミスした時に気づくのが遅れるから、握りつぶしに近い。

2017-12-07 03:23 UTC, mono0926 requested changes
![32_](https://user-images.githubusercontent.com/1255062/33697269-6fdec196-db49-11e7-903d-ed8c93a7e996.png)

2017-12-07 03:23 UTC, mono0926 commented
面倒くさそうなコンフリクト発生している(　´･‿･｀)

2017-12-07 03:28 UTC, mono0926 requested changes
[このコメント無視して]

2017-12-07 03:29 UTC, mono0926 requested changes
あれ、ここに書いたレビューが一覧に出てこないような。

2017-12-07 03:32 UTC, mono0926 commented on Miso.TrackingMealApp/TrackingMealApp/MealTableViewController.swift
> +            logger.debug("no found meal:\(meal.id) \(meal.name)")
ちなみに、ここはプログラムミスしなければ到達しないはずなので、assertionFailureかlogger.fatal、あるいはその両方が適切に思う。

そこそこ頻度があるエラー(APIから返るエラーレスポンスとか？)は、infoかerrorレベルのログにしてる。

2017-12-07 03:33 UTC, mono0926 commented
https://github.com/hhyyg/Miso.iOSPractice/pull/4/commits/61fe16c9aa4d9f941a5e0e568e08eeccf9b484d7#r155422018 のレビューがここの一覧に出てこない 🤔

2017-12-07 03:33 UTC, mono0926 commented
そういえばGitHubのコメントの挙動がおかしかったのが直ったかも。

2017-12-07 04:53 UTC, merged